config/routes.rb
Ivrsystem::Application.routes.draw do
 
 resources :welcome_options
 resources :yammer_auth
 match 'screen' => 'screening#screen', via: [:get, :post], as: "sceening_screen"
 match 'connect' => 'screening#connect', via: [:get, :post], as: "screening_connect"
 match 'log_and_alert' => 'recording#log_and_alert', via: [:get, :post], as: "log_and_alert"

end

app/controllers/yammer_auth_controller.rb
class YammerAuthController < SecureBaseController


  
  #sign in with Yammer
  def index
    @auth_url = "https://www.yammer.com/dialog/oauth?client_id=#{ENV['yammer_client_id']}&redirect_uri=#{redirect_url}"
  end
  
  #oAuth Accept
  def new
  #  yammer_client = Yammer::OAuth2Client.new(ENV['yammer_client_id'], ENV['yammer_client_secret'])
   # response_raw = yammer_client.access_token_from_authorization_code(params[:code], {redirect_uri:ENV['yammer_redirect_uri']})
   
   begin
      token = client.auth_code.get_token(params[:code], :redirect_uri => redirect_url)
      yammer_response = JSON.parse(token.token.gsub(/:([a-zA-z])/,'\\1').gsub('=>', ' : ').gsub('nil','""')) 
    
      auth_token = yammer_response["token"]
      ap = AppConfig.find_by_name("threesparks")
      ap.yammer_auth_token=auth_token
      ap.save
       flash[:notice]="Yamemr Authentication is ready"
    rescue
      if ap.yammer_auth_token.blank?
        flash[:notice]="Authentication Failed, please try again"
      else
        flash[:notice]="Yamemr Authentication is ready"
      end
    end


  end
  
  def client
    YammerConnect.oauth_client
  end 
    
  def redirect_url
    ENV['yammer_redirect_uri']
  end
  
 
  
end

app/views/yammer_auth/index.html.erb
<html>
<body>
	<h1>Authenicate your Yammer account with IVR System<h1>
		<p>IVR System will use your Yammer account to post voicemail notifications to Yammer</p>
		
		<a href="<%=raw @auth_url%>">Sign in with Yammer</a>
</body>
</html>

app/views/yammer_auth/new.html.erb
<html>
<body>
	<h1><%=flash[:notice]%><h1>
		<p><%= link_to "Click here", yammer_auth_index_path%> to change authenticated user or refresh authentication<p>
</body>
</html>